"""Updated column

Revision ID: 047042a3af12
Revises: 178914204f7a
Create Date: 2025-06-14 03:13:16.442597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "047042a3af12"
down_revision: Union[str, None] = "178914204f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trajectories", sa.Column("chat", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trajectories", "chat")
    # ### end Alembic commands ###
