"""Updated column

Revision ID: 05293c942a0a
Revises: 9af824b568f8
Create Date: 2025-06-03 06:13:35.311188

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "05293c942a0a"
down_revision: Union[str, None] = "9af824b568f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
