"""Updated column

Revision ID: 178914204f7a
Revises: 571179a07880
Create Date: 2025-06-14 02:09:59.515246

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "178914204f7a"
down_revision: Union[str, None] = "571179a07880"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
