"""Updated column

Revision ID: 1d3c21474753
Revises: 9cdbdf921419
Create Date: 2025-05-07 07:13:27.480035

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1d3c21474753"
down_revision: Union[str, None] = "9cdbdf921419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
