"""Updated column

Revision ID: 339254e6cb64
Revises: bad56b6a201e
Create Date: 2025-07-20 13:25:21.577698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "339254e6cb64"
down_revision: Union[str, None] = "bad56b6a201e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("defense_harness_steps", sa.Column("defense_experiment_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_defense_harness_steps_defense_experiment_id"),
        "defense_harness_steps",
        ["defense_experiment_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "defense_harness_steps",
        "defense_harness_experiments",
        ["defense_experiment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "defense_harness_steps", type_="foreignkey")
    op.drop_index(op.f("ix_defense_harness_steps_defense_experiment_id"), table_name="defense_harness_steps")
    op.drop_column("defense_harness_steps", "defense_experiment_id")
    # ### end Alembic commands ###
