"""Updated column

Revision ID: 3be8ceff2f78
Revises: 6f40ad61837e
Create Date: 2025-07-15 14:31:24.103400

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3be8ceff2f78"
down_revision: Union[str, None] = "6f40ad61837e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('experiments', sa.Column('task_success_rate', sa.Float(), sa.Computed("\n            CASE \n                WHEN (SELECT COUNT(*) FROM trajectories WHERE experiment_id = id) = 0 THEN 0\n                ELSE ROUND(\n                    CAST(\n                        (SELECT COUNT(*) \n                         FROM trajectories \n                         WHERE experiment_id = id \n                           AND (trajectory->>'reward')::float = 1.0\n                        ) AS NUMERIC\n                    ) / \n                    CAST(\n                        (SELECT COUNT(*) \n                         FROM trajectories \n                         WHERE experiment_id = id\n                        ) AS NUMERIC\n                    ),\n                    4\n                )\n            END\n            ", persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('experiments', 'task_success_rate')
    # ### end Alembic commands ###
