"""Updated column

Revision ID: 444a4e78ec23
Revises: d2f9369b1397
Create Date: 2025-05-11 01:44:31.597068

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "444a4e78ec23"
down_revision: Union[str, None] = "d2f9369b1397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("experiments", sa.Column("is_running", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiments", "is_running")
    # ### end Alembic commands ###
