"""Updated column

Revision ID: 4941c697cf91
Revises: e8ddab714b88
Create Date: 2025-07-06 16:25:00.183584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4941c697cf91"
down_revision: Union[str, None] = "e8ddab714b88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_screenshots_v2_observation_id", table_name="screenshots_v2")
    op.drop_table("screenshots_v2")
    op.add_column("experiments", sa.Column("hidden", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiments", "hidden")
    op.create_table(
        "screenshots_v2",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("observation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["observations_v2.id"], name="screenshots_v2_observation_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="screenshots_v2_pkey"),
    )
    op.create_index("ix_screenshots_v2_observation_id", "screenshots_v2", ["observation_id"], unique=False)
    # ### end Alembic commands ###
