"""Updated column

Revision ID: 4a2471e87b6d
Revises: 339254e6cb64
Create Date: 2025-07-20 14:29:00.255578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a2471e87b6d"
down_revision: Union[str, None] = "339254e6cb64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("defense_harness_steps", sa.Column("error_message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("defense_harness_steps", "error_message")
    # ### end Alembic commands ###
