"""Updated column

Revision ID: 4c8d268ccd5a
Revises: 4dda0b607645
Create Date: 2025-08-19 11:13:01.830629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c8d268ccd5a'
down_revision: Union[str, None] = '4dda0b607645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defense_harness_steps', sa.Column('async_messages_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defense_harness_steps', 'async_messages_stats')
    # ### end Alembic commands ###
