"""Updated column

Revision ID: 4dda0b607645
Revises: c56538ecbb59
Create Date: 2025-08-17 22:17:11.011924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dda0b607645'
down_revision: Union[str, None] = 'c56538ecbb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defense_harness_steps', sa.Column('relevant_cap_set', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defense_harness_steps', 'relevant_cap_set')
    # ### end Alembic commands ###
