"""Updated column

Revision ID: 571179a07880
Revises: 05293c942a0a
Create Date: 2025-06-12 06:49:10.215139

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "571179a07880"
down_revision: Union[str, None] = "05293c942a0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
