"""Updated column

Revision ID: 6f40ad61837e
Revises: 9535cd36c47b
Create Date: 2025-07-15 14:30:00.189822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f40ad61837e"
down_revision: Union[str, None] = "9535cd36c47b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trajectories", "evaluation_results")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trajectories",
        sa.Column("evaluation_results", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
