"""Updated column

Revision ID: 78e86aa48ca2
Revises: 1d3c21474753
Create Date: 2025-05-10 23:20:41.366300

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "78e86aa48ca2"
down_revision: Union[str, None] = "1d3c21474753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
