"""Updated column

Revision ID: 7e1b8f536d07
Revises: d2abded1a9c9
Create Date: 2025-05-07 04:41:11.804088

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7e1b8f536d07"
down_revision: Union[str, None] = "d2abded1a9c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
