"""Updated column

Revision ID: 872d6f36fb01
Revises: 4a2471e87b6d
Create Date: 2025-07-21 14:47:28.821887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872d6f36fb01'
down_revision: Union[str, None] = '4a2471e87b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defense_harness_steps', sa.Column('llm_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defense_harness_steps', 'llm_logs')
    # ### end Alembic commands ###
