"""Updated column

Revision ID: 9535cd36c47b
Revises: b71e39a222c4
Create Date: 2025-07-15 14:26:52.515531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9535cd36c47b"
down_revision: Union[str, None] = "b71e39a222c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trajectories",
        sa.Column(
            "success", sa.Boolean(), sa.Computed("(trajectory->>'reward')::float > 0", persisted=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trajectories", "success")
    # ### end Alembic commands ###
