"""Updated column

Revision ID: 9af824b568f8
Revises: 444a4e78ec23
Create Date: 2025-05-12 10:26:58.705065

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9af824b568f8"
down_revision: Union[str, None] = "444a4e78ec23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("observations_v2_trajectory_id_fkey", "observations_v2", type_="foreignkey")
    op.create_foreign_key(None, "observations_v2", "trajectories", ["trajectory_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("screenshots_v2_observation_id_fkey", "screenshots_v2", type_="foreignkey")
    op.create_foreign_key(None, "screenshots_v2", "observations_v2", ["observation_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("trajectories_experiment_id_fkey", "trajectories", type_="foreignkey")
    op.create_foreign_key(None, "trajectories", "experiments", ["experiment_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trajectories", type_="foreignkey")
    op.create_foreign_key("trajectories_experiment_id_fkey", "trajectories", "experiments", ["experiment_id"], ["id"])
    op.drop_constraint(None, "screenshots_v2", type_="foreignkey")
    op.create_foreign_key(
        "screenshots_v2_observation_id_fkey", "screenshots_v2", "observations_v2", ["observation_id"], ["id"]
    )
    op.drop_constraint(None, "observations_v2", type_="foreignkey")
    op.create_foreign_key(
        "observations_v2_trajectory_id_fkey", "observations_v2", "trajectories", ["trajectory_id"], ["id"]
    )
    # ### end Alembic commands ###
