"""Updated column

Revision ID: 9cdbdf921419
Revises: 7e1b8f536d07
Create Date: 2025-05-07 07:10:41.383999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cdbdf921419"
down_revision: Union[str, None] = "7e1b8f536d07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observations")
    op.drop_index("ix_agent_experiments_task_ids", table_name="agent_experiments")
    op.drop_table("agent_experiments")
    op.drop_table("screenshots")
    op.drop_constraint("experiments_name_key", "experiments", type_="unique")
    op.create_index(op.f("ix_experiments_name"), "experiments", ["name"], unique=True)
    op.create_index(op.f("ix_observations_v2_trajectory_id"), "observations_v2", ["trajectory_id"], unique=False)
    op.create_index(op.f("ix_screenshots_v2_observation_id"), "screenshots_v2", ["observation_id"], unique=False)
    op.create_index(op.f("ix_trajectories_experiment_id"), "trajectories", ["experiment_id"], unique=False)
    op.create_index(op.f("ix_trajectories_task_id"), "trajectories", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trajectories_task_id"), table_name="trajectories")
    op.drop_index(op.f("ix_trajectories_experiment_id"), table_name="trajectories")
    op.drop_index(op.f("ix_screenshots_v2_observation_id"), table_name="screenshots_v2")
    op.drop_index(op.f("ix_observations_v2_trajectory_id"), table_name="observations_v2")
    op.drop_index(op.f("ix_experiments_name"), table_name="experiments")
    op.create_unique_constraint("experiments_name_key", "experiments", ["name"])
    op.create_table(
        "screenshots",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="screenshots_pkey"),
    )
    op.create_table(
        "agent_experiments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("trajectory", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("task_ids", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column("experiment_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("experiment_group", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("evaluation_results", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("observations", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="agent_experiments_pkey"),
    )
    op.create_index("ix_agent_experiments_task_ids", "agent_experiments", ["task_ids"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="observations_pkey"),
    )
    # ### end Alembic commands ###
