"""username

Revision ID: ab02de2b23ca
Revises: b6fb7d124da0
Create Date: 2025-07-06 17:44:39.169503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab02de2b23ca"
down_revision: Union[str, None] = "b6fb7d124da0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("error_logs", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("error_logs", "username")
    # ### end Alembic commands ###
