"""Updated column

Revision ID: b6fb7d124da0
Revises: 4941c697cf91
Create Date: 2025-07-06 16:26:50.652297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6fb7d124da0"
down_revision: Union[str, None] = "4941c697cf91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("experiments", sa.Column("favorite", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiments", "favorite")
    # ### end Alembic commands ###
