"""Updated column

Revision ID: b71e39a222c4
Revises: ab02de2b23ca
Create Date: 2025-07-12 11:43:31.656022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b71e39a222c4"
down_revision: Union[str, None] = "ab02de2b23ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_screenshots_v2_observation_id", table_name="screenshots_v2")
    op.drop_table("screenshots_v2")
    op.create_index("uix_experiment_task", "trajectories", ["experiment_id", "task_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_experiment_task", table_name="trajectories")
    op.create_table(
        "screenshots_v2",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("observation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["observations_v2.id"], name="screenshots_v2_observation_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="screenshots_v2_pkey"),
    )
    op.create_index("ix_screenshots_v2_observation_id", "screenshots_v2", ["observation_id"], unique=False)
    # ### end Alembic commands ###
