"""new col

Revision ID: bad56b6a201e
Revises: 3be8ceff2f78
Create Date: 2025-07-17 19:40:57.082155

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bad56b6a201e"
down_revision: Union[str, None] = "3be8ceff2f78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("observations_v2", sa.Column("step_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observations_v2", "step_number")
    # ### end Alembic commands ###
