"""Updated column

Revision ID: c56538ecbb59
Revises: 872d6f36fb01
Create Date: 2025-07-21 16:09:11.585874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56538ecbb59'
down_revision: Union[str, None] = '872d6f36fb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defense_harness_steps', sa.Column('input_tokens', sa.Integer(), sa.Computed('sum_input_tokens(llm_logs)', persisted=True), nullable=True))
    op.add_column('defense_harness_steps', sa.Column('cached_input_tokens', sa.Integer(), sa.Computed('sum_cached_input_tokens(llm_logs)', persisted=True), nullable=True))
    op.add_column('defense_harness_steps', sa.Column('output_tokens', sa.Integer(), sa.Computed('sum_output_tokens(llm_logs)', persisted=True), nullable=True))
    op.add_column('defense_harness_steps', sa.Column('total_request_time', sa.Numeric(), sa.Computed('sum_request_duration(llm_logs)', persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defense_harness_steps', 'total_request_time')
    op.drop_column('defense_harness_steps', 'output_tokens')
    op.drop_column('defense_harness_steps', 'cached_input_tokens')
    op.drop_column('defense_harness_steps', 'input_tokens')
    # ### end Alembic commands ###
