"""Updated column

Revision ID: cd58d6cf1910
Revises: f21dfa794c89
Create Date: 2025-07-03 15:29:36.121042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd58d6cf1910"
down_revision: Union[str, None] = "f21dfa794c89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trajectories", "environment_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trajectories", sa.Column("environment_logs", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
