"""Updated column

Revision ID: d2abded1a9c9
Revises: 3d3dcf23acf1
Create Date: 2025-05-05 23:35:38.249981

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d2abded1a9c9"
down_revision: Union[str, None] = "3d3dcf23acf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
