"""Updated column

Revision ID: d2f9369b1397
Revises: 78e86aa48ca2
Create Date: 2025-05-10 23:21:15.126101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2f9369b1397"
down_revision: Union[str, None] = "78e86aa48ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("experiments", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiments", "description")
    # ### end Alembic commands ###
