"""Updated column

Revision ID: e8ddab714b88
Revises: 59401ec59bed
Create Date: 2025-07-06 11:23:27.592534

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e8ddab714b88"
down_revision: Union[str, None] = "59401ec59bed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
