"""make error_logs & function_timings unlogged

Revision ID: fb1256ed6725
Revises: 1a52f357a6c8
Create Date: 2025-06-19 04:05:00.113947

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb1256ed6725"
down_revision: Union[str, None] = "1a52f357a6c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE error_logs SET UNLOGGED;")
    op.execute("ALTER TABLE function_timings SET UNLOGGED;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
